services:
  postgres:
    image: postgres:13.2
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./docker/dev/.env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
